trigger:    
- main    #branch

resources:  
- repo: self    #self repo

variables:
- group: CICD
- name: appVersion
  value: $[variables.appVersion]

parameters:
  - name: tag
    default: tag: '$(Build.BuildId)' #identifier of build, # of build/version
  - name: imageName
    default: 'demo-page'

stages:
- stage: Build
  displayName: Build image
  jobs:   #Executions
  - job: Build
    displayName: Build
    pool:  local-agent
    
    steps:
    - task: Docker@2  #like a Docker image v2
      displayName: Build an image
      inputs:
        repository: ${{ parameters.imageName}}  #taken from parameters
        command: build
        dockerfile: '**/Dockerfile' #double ** so it searches anywhere
        tags: ${{ parameters.tag}} #Taked form parameters
        arguments: '--build-arg VERSION=$(appVersion)'
        containerRegistry: registryConnection

    - task: Docker@2
      displayName: Push to ACR
      inputs:
        command: push
        containerRegistry: registryConnection
        repository: ${{ parameters.imageName}}
        tags: ${{ parameters.tag }}